# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b202980baea2923e9e75a336f06f77fec28e290f599827c4c197b2aa8d6710c69d943480c3531c0843e2b944ade51b9f06b0aef49a6552f93536ecb4f62bcd7d

test:
  secret_key_base: 0e9fbdbbf20e05033a594d0c8bf67b32b0c35046f967dd2dccdeee156ac3c87ede6f03ee4e7fb0768559ebefd648583497d8d42067ac5bb4266913181cc0af77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
